### ISSUE TITLE
dosage 2.15 doesn't work on windows

### ISSUE THREAD

**Issue by frozenworks** [wummel/dosage#82]
I recently updated my version of dosage and the new windows version doesn't appear to work.
When I try running it I get this response 

dosage MegaTokyo  --continue
Traceback (most recent call last):
  File "dosage", line 18, in <module>
  File "dosagelib\events.pyo", line 11, in <module>
  File "dosagelib\util.pyo", line 17, in <module>
  File "requests__init__.pyo", line 58, in <module>
  File "requests\utils.pyo", line 25, in <module>
  File "requests\compat.pyo", line 7, in <module>
  File "requests\packages__init__.pyo", line 3, in <module>
  File "requests\packages\urllib3__init__.pyo", line 16, in <module>
  File "requests\packages\urllib3\connectionpool.pyo", line 39, in <module>
  File "requests\packages\urllib3\request.pyo", line 12, in <module>
  File "requests\packages\urllib3\filepost.pyo", line 15, in <module>
  File "requests\packages\urllib3\fields.pyo", line 7, in <module>
ImportError: No module named email.utils

I am using the windows exe version of dosage.

**Comment by donnachaidh** [comment]
I am getting the same error. How can I get the older version that does work?

**Comment by TobiX** [comment]
Unfortunately, @wummel seems to be MIA since some time and can't make a new release... You can always install Python manually instead of using the standalone installer, if you are experienced with Python. I can write a short guide if requested.

You can download http://wummel.github.io/dosage/dist/dosage-2.11.exe for the old version...

**Comment by JustJordon** [comment]
If anyone's still having this problem, it's an easy fix. Go to where dosage is installed, which for me is the scripts folder in my python folder. Then rename the file called dosage to dosage.py

**Comment by TobiX** [comment]
@JustJordon That's only a fix for people not using the Windows installer. I'm currently a bit short on free time, but I'm aiming for a package similar to youtube-dl, where the whole distribution and all dependencies are packaged into the .exe file. I recently noticed that depending directly on pycountry wasn't that smart a move on my part, since it can't be packaged into an archive :(

**Comment by afro-dadzie** [comment]
sorry to bump a solved issue, but I'm getting the same error and renaming the dosage file hasn't solved it?
